/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.bullrich;


public class Exercise1Variables {


    public static void main(String[] args) {
        // Create 2 variables, one of type int and one of type long

        // Using this method (copy it the times that you need) print both variables
        System.out.println();

        // then print the sum of each variable

        // The, make a boolean, that it's equal to the first valuable being GREATER than the second variable
    }
}
